language: python
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - pypy2.7-6.0

install:
  - pip install coveralls tox-travis

script:
  - tox -- --cov-append

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOX_ENV=docs
      script: tox -e $TOX_ENV
    - python: "3.6"
      env: TOX_ENV=flake8
      script: tox -e $TOX_ENV

after_success:
  - coveralls
